CREATE TABLE IF NOT EXISTS avaliacoes (
  id INT NOT NULL AUTO_INCREMENT,
  curso VARCHAR(100) NOT NULL,
  avaliacao VARCHAR(100) NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  pontos INT NOT NULL,
  status VARCHAR(20) DEFAULT NULL,
  nota INT DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
